# Generated by Django 4.2 on 2023-09-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_buyer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=-121212),
        ),
    ]
