# Generated by Django 4.2 on 2023-09-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_buyer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
