# Generated by Django 4.2 on 2023-09-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_buyer_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='User',
        ),
    ]
